version: '3.1'


services:
  db:
    image: postgres:13.1
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: egor
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: db
    
  backend:
    build: ./drf
    privileged: true
    ports:
      - 8081:8081
    command:
      bash -c "python3 manage.py migrate && python manage.py fill_db &&
      gunicorn drf.wsgi -b 0.0.0.0:8081"
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - nginx